create table if not exists public.rates (
 id bigint generated by default as identity primary key,
 co_ve numeric(12,4) not null,
 ve_co numeric(12,4) not null,
 usd_colombia numeric(14,2) not null,
 usd_venezuela numeric(14,2) not null,
 valid_from date not null,
 valid_to date null,
 notes text default '',
 created_at timestamptz default now()
);
alter table public.rates enable row level security;
create index if not exists rates_dates on public.rates(valid_from,valid_to);
insert into public.rates(co_ve,ve_co,usd_colombia,usd_venezuela,valid_from,notes)
select 3.98,3.00,3330.00,855.66,current_date,'Tasa inicial Dorca Conecta'
where not exists(select 1 from public.rates);
